### ISSUE TITLE
Does this guide need translate?

### ISSUE THREAD

**Issue by einverne** [cirosantilli/markdown-style-guide#1]
I can help with the Chinese translation.

**Comment by cirosantilli** [comment]
That would be awesome @einverne !

However I don't want to merge it here because it would generate too much maintenance overhead for me.

I propose this: make the translation on a separate personal repo.

When the translation reaches some maturity, I will link to it from the English version, promised :-)

I would also recommend translating a specific revision: e.g. say clearly on your repo: this translates commit XXX , or even better, include this as a submodule. But of course, that is up to you.

My desire is to keep most of my projects GPL. Time to add a license to this repo.

**Comment by einverne** [comment]
I have finished my first version translation. http://einverne.github.io/markdown-style-guide/zh.html

**Comment by cirosantilli** [comment]
@einverne Great! I've linked to your guide at: http://www.cirosantilli.com/markdown-style-guide/#about

I've also decided to use a CC BY SA license: https://github.com/cirosantilli/markdown-style-guide/blob/gh-pages/LICENSE.md Please add it to your project. I think you can then update the License file to something like:

```
## License

<in chinese>Your title by Your name is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. Based on a work at <your url>

Adapted from <copy paste my license>Markdown Style Guide by Ciro Santilli is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. Based on a work at http://www.cirosantilli.com/markdown-style-guide.
```

Let me know if you find a better way, I'm new to licensing matters.

**Comment by einverne** [comment]
I have updated License file and merged your changes into my translations.

https://github.com/einverne/markdown-style-guide/blob/gh-pages/LICENSE.md
